//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorKober.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPreciosD
    {
        public string Lista { get; set; }
        public string Moneda { get; set; }
        public string Articulo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string CodigoCliente { get; set; }
        public Nullable<double> Margen { get; set; }
        public string Region { get; set; }
        public string TMEws_id { get; set; }
        public string TMEws_status { get; set; }
    }
}
